# Generated by Django 6.0.1 on 2026-02-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_aboutsection_delete_contactmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('fa-bowl-rice', 'Rice Bowl'), ('fa-filter', 'Filter'), ('fa-wheat-awn', 'Wheat'), ('fa-seedling', 'Seedling'), ('fa-industry', 'Industry')], default='fa-bowl-rice', max_length=50),
        ),
    ]
