# Generated by Django 6.0.1 on 2026-02-21 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_service_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='homeService',
        ),
    ]
