# Generated by Django 6.0.1 on 2026-02-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_service_homeservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='our_services/')),
            ],
            options={
                'verbose_name': 'Our Service',
                'verbose_name_plural': 'Our Services',
            },
        ),
    ]
