# Generated by Django 6.0.1 on 2026-02-21 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_ourservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourservice',
            options={},
        ),
    ]
